apiVersion: v1
kind: Service
metadata:
  name: trainer-model-registry
  namespace: sentiment-analyzer
  labels:
    app: trainer-model-registry
spec:
  type: ClusterIP
  selector:
    app: trainer-model-registry
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9108
    targetPort: metrics
    protocol: TCP
  sessionAffinity: None
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trainer-model-registry
  namespace: sentiment-analyzer
  labels:
    app: trainer-model-registry
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: trainer-model-registry
  namespace: sentiment-analyzer
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trainer-model-registry
  namespace: sentiment-analyzer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: trainer-model-registry
subjects:
- kind: ServiceAccount
  name: trainer-model-registry
  namespace: sentiment-analyzer

