apiVersion: v1
kind: Secret
metadata:
  name: labeler-secrets
  namespace: sentiment-analyzer
type: Opaque
stringData:
  postgres_user: "adminsentiment"
  postgres_password: "wp2400!!!!"
  acled_api_key: "YOUR_ACLED_API_KEY_HERE"

