apiVersion: v1
kind: Service
metadata:
  name: labeler-ground-truth-ingest-service
  namespace: sentiment-analyzer
  labels:
    app: labeler-ground-truth-ingest-service
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9107
    targetPort: 9107
    protocol: TCP
  selector:
    app: labeler-ground-truth-ingest-service

