apiVersion: v1
kind: Secret
metadata:
  name: embedding-secrets
  namespace: sentiment-analyzer
type: Opaque
stringData:
  postgres.user: "adminsentiment"
  postgres.password: "wp2400!!!!"
  qdrant.api_key: ""
  redis.password: ""

