apiVersion: v1
kind: Service
metadata:
  name: api-analytics-service
  namespace: sentiment-analyzer
  labels:
    app: api-analytics-service
spec:
  type: ClusterIP
  selector:
    app: api-analytics-service
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9111
    targetPort: metrics
    protocol: TCP
  sessionAffinity: None

