apiVersion: v1
kind: Service
metadata:
  name: {{ include "ner-entity-linking-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ner-entity-linking-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "ner-entity-linking-service.selectorLabels" . | nindent 4 }}

