apiVersion: v1
kind: Service
metadata:
  name: crawler-service
  namespace: crawler-service
  labels:
    app: crawler-service
spec:
  type: ClusterIP
  selector:
    app: crawler-service
  ports:
  - name: metrics
    port: 9101
    targetPort: 9101
    protocol: TCP
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: crawler-service-headless
  namespace: crawler-service
  labels:
    app: crawler-service
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: crawler-service
  ports:
  - name: metrics
    port: 9101
    targetPort: 9101
    protocol: TCP

