apiVersion: v1
kind: Secret
metadata:
  name: {{ include "embedding-service.fullname" . }}
  labels:
    {{- include "embedding-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgres.password | quote }}

